### PR TITLE
Add libvirt_domain_job metrics

### PR DESCRIPTION
**Pull request by korservick**
Add domain job metrics to monitor VM migration process.

### CODE REVIEW

**Comment by frittentheke** [comment]
Sorry @korservick for the insanely slow reply. Thanks for your contribution!

**Comment by frittentheke** [comment]
@korservick could you kindly provide some ideas on how to test this with a running VM?

* https://www.libvirt.org/manpages/virsh.html#save ?
* https://www.libvirt.org/manpages/virsh.html#backup-begin ?
* ...

**Comment by korservick** [comment]
@frittentheke when the virtual machine is running, these metrics do not exist. They begin to provide some useful information only when VMs migrate from one host to another. Virsh stops generating job metrics from host after VM migration

**Comment by frittentheke** [comment]
@korservick We just tested this, but the metrics from migration are very short lived, as the job is short lived. So the sampling rate does need to be really high. 

I gladly take this contribution, but was simply uncertain if this even provides other valuable measurements apart from very long running migrations?

**Comment by korservick** [comment]
@frittentheke we have quite large VMs and local disk throttling is additionally enabled (for VMs not on shared storage) so as not to affect the performance of other VMs. For this reason, live migration can take from 10 minutes to 2 hours (rebalancing the load on the hosts). 
In the version of virsh we use, throttling is set by one parameter that limits both the disk copying speed and the RAM copying speed. Some VMs enter perpetual migration mode (data in RAM changes faster than it migrates). This is why this patch with additional metrics was written.
Of course, for very fast migrations this metric is not needed. If it does not fall within the scraping interval, then of course these metrics are not needed.

**Comment by korservick** [comment]
@frittentheke you can set migration speed by this comand: virsh migrate-setspeed VMID 100

**Pull request merged**
